[package]
name = "date-group"
description = "Group a directory of files by date"
version = "0.1.0"
authors = ["Jake Howard <git@theorangeone.net>"]
edition = "2018"
repository = "https://github.com/RealOrangeOne/date-group"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
structopt = "0.3.14"
glob = "0.3.0"
kamadak-exif = "0.5.1"
dtparse = "1.0.3"
chrono = "0.4.6"
indicatif = "0.14.0"
console = "0.11.3"
lazy_static = "1.4.0"
