[package]
name = "date-group"
version = "0.1.0"
authors = ["Jake Howard <git@theorangeone.net>"]
edition = "2018"

[dependencies]
structopt = "0.3.14"
glob = "0.3.0"
kamadak-exif = "0.5.1"
dtparse = "1.0.3"
chrono = "0.4.6"
indicatif = "0.14.0"
