name: Release

on: [push]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: $HOME/.cargo
          key: cargo-${{ hashFiles('Cargo.lock') }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-deb
        uses: actions-rs/install@v0.1
        if: matrix.os == "ubuntu-latest"
        with:
          crate: cargo-deb
          use-tool-cache: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Build deb
        uses: actions-rs/cargo@v1
        if: matrix.os == "ubuntu-latest"
        with:
          command: deb
